# SPDX-FileCopyrightText: Copyright 2025 Florian Albrechtskirchinger <falbrechtskirchinger@gmail.com>
#
# SPDX-License-Identifier: MIT

name: ğŸ›¡ï¸ Merge ebuild (beta)

on:
  workflow_run:
    workflows: ['ğŸ§ª Merge ebuilds']
    types: [completed]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect test results
        id: test-results
        run: python scripts/test_ebuilds.py -v --collect-test-results --from-event --read-variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.INTEGRATION_PAT }}

      - name: Report status
        run: |
          if [[ -z "${{ fromJSON(steps.test-results.outputs.test_results).beta.conclusion }}" ]]; then
            echo "âš ï¸ No 'beta' test result available."
            exit 1
          elif [[ "${{ fromJSON(steps.test-results.outputs.test_results).beta.cached }}" == "true" ]]; then
            echo "ğŸ’¡ Test result is cached."
          fi

          if [[ "${{ fromJSON(steps.test-results.outputs.test_results).beta.conclusion }}" == "success" ]]; then
            echo "âœ… 'Beta' ebuild merge succeeded."
            exit 0
          else
            echo "âŒ 'Beta' ebuild merge failed."
            exit 1
          fi
