# SPDX-FileCopyrightText: Copyright 2025 Florian Albrechtskirchinger <falbrechtskirchinger@gmail.com>
#
# SPDX-License-Identifier: MIT

name: üõ°Ô∏è Merge ebuild (nightly)

on:
  workflow_run:
    workflows: ['üß™ Merge ebuilds']
    types: [completed]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect test results
        id: test-results
        run: python scripts/test_ebuilds.py -v --collect-test-results --from-event --read-variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.INTEGRATION_PAT }}

      - name: Report status
        run: |
          if [[ -z "${{ fromJSON(steps.test-results.outputs.test_results).nightly.conclusion }}" ]]; then
            echo "‚ö†Ô∏è No 'nightly' test result available."
            exit 1
          elif [[ "${{ fromJSON(steps.test-results.outputs.test_results).nightly.cached }}" == "true" ]]; then
            echo "üí° Test result is cached."
          fi

          if [[ "${{ fromJSON(steps.test-results.outputs.test_results).nightly.conclusion }}" == "success" ]]; then
            echo "‚úÖ 'Nightly' ebuild merge succeeded."
            exit 0
          else
            echo "‚ùå 'Nightly' ebuild merge failed."
            exit 1
          fi
